# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96e77ffb24b30e5743a8be1d8d6c2107052c34ef8321fab02eba70bb4df04a667c39fe7ef5c3861b91942a8dbdadd5716a2cb6d6b04cfbc093160ac255076c32

test:
  secret_key_base: 472e1f8532564cb627567021fbe230f18f9a4ea855d1d0bbb11c5d8a2401a64ef7700254d7e9d3e95cc45a542a7a8d3a0b71d215b35660dc1b02c4bab9ee02d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
